### ISSUE TITLE
Message que

### ISSUE THREAD

**Issue by askdesigners** [askdesigners/bedrock-weeds#56]
## References
- https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04#configure-redis
- https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-14-04
- https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-16-04

## Todo
- [x] redis setup and config
- [x] redis connection on limestone
- [x] redis connection on magma
- [x] Limestone create messages
- [x] Limestone receive messages
- [x] Magma receive messages (replace API structure)
- [x] Magma create messages
